# Generated by Django 3.2.6 on 2021-09-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('stock_market', models.CharField(db_column='stock_market', max_length=10)),
                ('stock_code', models.CharField(db_column='stock_code', max_length=10, unique=True)),
                ('stock_name', models.CharField(db_column='stock_name', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'stocks',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('open_price', models.IntegerField(db_column='open_price')),
                ('high_price', models.IntegerField(db_column='high_price')),
                ('low_price', models.IntegerField(db_column='low_price')),
                ('close_price', models.IntegerField(db_column='close_price')),
                ('date', models.DateField(db_column='date')),
                ('stocks_id', models.ForeignKey(db_column='stocks_id', on_delete=django.db.models.deletion.DO_NOTHING, to='sample.stocks')),
            ],
            options={
                'db_table': 'stock_price',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
