# Generated by Django 3.2.6 on 2021-09-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_stockprice_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='stock_market',
        ),
    ]
